version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 travelo.wsgi:application  # Changed to 8000
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app  # اتصال دایرکتوری اپلیکیشن به nginx

    ports:
      - "80:80"
    depends_on:
      - web
