# Generated by Django 4.2.16 on 2024-10-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='login_requier',
            field=models.BooleanField(default=False),
        ),
    ]
