# Generated by Django 4.2.16 on 2024-10-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_login_requier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='login_requier',
        ),
        migrations.AddField(
            model_name='post',
            name='login_requier',
            field=models.BooleanField(default=False),
        ),
    ]
