# Generated by Django 4.2.16 on 2024-10-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatc',
            new_name='Contatct',
        ),
    ]
